# Build settings

#port: 4000
markdown:  kramdown
permalink: /:title.html
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		   "Gean Ramos"
description: "Powered by Jekyll and GitHub Pages"
author:      "Gean Ramos"
# imgcdn:      "https://i1.wp.com/geanramos.github.com/portfolio-jekyll-theme/"
