#-------------------------------
# General Site Settings

menu:
- {name: 'Projetos', url: ''}
- {name: 'Blog',     url: 'blog'}
- {name: 'Sobre',    url: 'about'}
- {name: 'Contato',  url: 'contact'}

#-------------------------------
# Projects Section

projects:
- {name: 'Projeto #1',   url: 'proj-1'}
- {name: 'Projeto #2',   url: 'proj-2'}
- {name: 'Projeto #3',   url: 'proj-3'}
- {name: 'Projeto #4',   url: 'proj-4'}
- {name: 'Projeto #5',   url: 'proj-5'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter',   link: 'https://twitter.com/geanramos'}
- {icon: 'instagram', link: 'https://instagram.com/geanramus'}
- {icon: 'linkedin',  link: 'https://linkedin.com/in/geanramos'}
- {icon: 'envelope',  link: 'mailto:mailto:geanramus@gmail.com'}
- {icon: 'rss',  link: './feed.xml'}
- {icon: 'shield-halved',  link: './privacidade'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: true #false
  disqus_shortname: 'geanramos'
